from typing import Any

class AMQPObject:
    NAME: str = ...
    INDEX: Any = ...
    def __eq__(self, other: Any) -> Any: ...

class Class(AMQPObject):
    NAME: str = ...

class Method(AMQPObject):
    NAME: str = ...
    synchronous: bool = ...
    def get_properties(self): ...
    def get_body(self): ...

class Properties(AMQPObject):
    NAME: str = ...
