from pika import amqp_object as amqp_object, frame as frame
from pika.compat import canonical_str as canonical_str, xrange as xrange
from typing import Any, Optional

LOGGER: Any

def name_or_value(value: Any): ...
def sanitize_prefix(function: Any): ...
def check_for_prefix_and_key(function: Any): ...

class CallbackManager:
    CALLS: str = ...
    ARGUMENTS: str = ...
    DUPLICATE_WARNING: str = ...
    CALLBACK: str = ...
    ONE_SHOT: str = ...
    ONLY_CALLER: str = ...
    def __init__(self) -> None: ...
    def add(self, prefix: Any, key: Any, callback: Any, one_shot: bool = ..., only_caller: Optional[Any] = ..., arguments: Optional[Any] = ...): ...
    def clear(self) -> None: ...
    def cleanup(self, prefix: Any): ...
    def pending(self, prefix: Any, key: Any): ...
    def process(self, prefix: Any, key: Any, caller: Any, *args: Any, **keywords: Any): ...
    def remove(self, prefix: Any, key: Any, callback_value: Optional[Any] = ..., arguments: Optional[Any] = ...): ...
    def remove_all(self, prefix: Any, key: Any) -> None: ...
