from pika.compat import dictkeys as dictkeys, is_integer as is_integer, unicode_type as unicode_type
from typing import Any, Optional

LOGGER: Any
MAX_CHANNELS: int

class Channel:
    CLOSED: int = ...
    OPENING: int = ...
    OPEN: int = ...
    CLOSING: int = ...
    channel_number: Any = ...
    callbacks: Any = ...
    connection: Any = ...
    flow_active: bool = ...
    def __init__(self, connection: Any, channel_number: Any, on_open_callback: Any) -> None: ...
    def __int__(self): ...
    def add_callback(self, callback: Any, replies: Any, one_shot: bool = ...) -> None: ...
    def add_on_cancel_callback(self, callback: Any) -> None: ...
    def add_on_close_callback(self, callback: Any) -> None: ...
    def add_on_flow_callback(self, callback: Any) -> None: ...
    def add_on_return_callback(self, callback: Any) -> None: ...
    def basic_ack(self, delivery_tag: int = ..., multiple: bool = ...): ...
    def basic_cancel(self, consumer_tag: str = ..., callback: Optional[Any] = ...) -> None: ...
    def basic_consume(self, queue: Any, on_message_callback: Any, auto_ack: bool = ..., exclusive: bool = ..., consumer_tag: Optional[Any] = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def basic_get(self, queue: Any, callback: Any, auto_ack: bool = ...) -> None: ...
    def basic_nack(self, delivery_tag: Optional[Any] = ..., multiple: bool = ..., requeue: bool = ...): ...
    def basic_publish(self, exchange: Any, routing_key: Any, body: Any, properties: Optional[Any] = ..., mandatory: bool = ...) -> None: ...
    def basic_qos(self, prefetch_size: int = ..., prefetch_count: int = ..., global_qos: bool = ..., callback: Optional[Any] = ...): ...
    def basic_reject(self, delivery_tag: Any, requeue: bool = ...): ...
    def basic_recover(self, requeue: bool = ..., callback: Optional[Any] = ...): ...
    def close(self, reply_code: int = ..., reply_text: str = ...) -> None: ...
    def confirm_delivery(self, ack_nack_callback: Any, callback: Optional[Any] = ...) -> None: ...
    @property
    def consumer_tags(self): ...
    def exchange_bind(self, destination: Any, source: Any, routing_key: str = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def exchange_declare(self, exchange: Any, exchange_type: str = ..., passive: bool = ..., durable: bool = ..., auto_delete: bool = ..., internal: bool = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def exchange_delete(self, exchange: Optional[Any] = ..., if_unused: bool = ..., callback: Optional[Any] = ...): ...
    def exchange_unbind(self, destination: Optional[Any] = ..., source: Optional[Any] = ..., routing_key: str = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def flow(self, active: Any, callback: Optional[Any] = ...) -> None: ...
    @property
    def is_closed(self): ...
    @property
    def is_closing(self): ...
    @property
    def is_open(self): ...
    def open(self) -> None: ...
    def queue_bind(self, queue: Any, exchange: Any, routing_key: Optional[Any] = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def queue_declare(self, queue: Any, passive: bool = ..., durable: bool = ..., exclusive: bool = ..., auto_delete: bool = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def queue_delete(self, queue: Any, if_unused: bool = ..., if_empty: bool = ..., callback: Optional[Any] = ...): ...
    def queue_purge(self, queue: Any, callback: Optional[Any] = ...): ...
    def queue_unbind(self, queue: Any, exchange: Optional[Any] = ..., routing_key: Optional[Any] = ..., arguments: Optional[Any] = ..., callback: Optional[Any] = ...): ...
    def tx_commit(self, callback: Optional[Any] = ...): ...
    def tx_rollback(self, callback: Optional[Any] = ...): ...
    def tx_select(self, callback: Optional[Any] = ...): ...

class ContentFrameAssembler:
    def __init__(self) -> None: ...
    def process(self, frame_value: Any): ...
