from io import StringIO as StringIO
from typing import Any
from urllib.parse import urlencode as urlencode, urlparse as urlparse

PY2: Any
PY3: Any
RE_NUM: Any
ON_LINUX: Any
ON_OSX: Any
ON_WINDOWS: Any
AbstractBase: Any
SOCKET_ERROR: Any
SOCKET_ERROR = OSError
SOL_TCP: Any
basestring: Any
str_or_bytes: Any
xrange = range
unicode_type = str

def time_now(): ...
def dictkeys(dct: Any): ...
def dictvalues(dct: Any): ...
def dict_iteritems(dct: Any): ...
def dict_itervalues(dct: Any): ...
def byte(*args: Any): ...

class long(int): ...

def canonical_str(value: Any): ...
def is_integer(value: Any): ...
def as_bytes(value: Any): ...
def to_digit(value: Any): ...
def get_linux_version(release_str: Any): ...

HAVE_SIGNAL: Any
EINTR_IS_EXPOSED: Any
LINUX_VERSION: Any
