from .compat import as_bytes as as_bytes
from typing import Any

LOGGER: Any

class PlainCredentials:
    TYPE: str = ...
    username: Any = ...
    password: Any = ...
    erase_on_connect: Any = ...
    def __init__(self, username: Any, password: Any, erase_on_connect: bool = ...) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def response_for(self, start: Any): ...
    def erase_credentials(self) -> None: ...

class ExternalCredentials:
    TYPE: str = ...
    erase_on_connect: bool = ...
    def __init__(self) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def response_for(self, start: Any): ...
    def erase_credentials(self) -> None: ...

VALID_TYPES: Any
