from pika import exceptions as exceptions
from pika.compat import PY2 as PY2, as_bytes as as_bytes, basestring as basestring, long as long, unicode_type as unicode_type
from typing import Any

def encode_short_string(pieces: Any, value: Any): ...
def decode_short_string(encoded: Any, offset: Any): ...
def encode_table(pieces: Any, table: Any): ...
def encode_value(pieces: Any, value: Any): ...
def decode_table(encoded: Any, offset: Any): ...
def decode_value(encoded: Any, offset: Any): ...
