from pika import frame as frame
from typing import Any

LOGGER: Any

class HeartbeatChecker:
    def __init__(self, connection: Any, timeout: Any) -> None: ...
    @property
    def bytes_received_on_connection(self): ...
    @property
    def connection_is_idle(self): ...
    def received(self) -> None: ...
    def stop(self) -> None: ...
