from pika.compat import basestring as basestring
from typing import Any

def require_string(value: Any, value_name: Any) -> None: ...
def require_callback(callback: Any, callback_name: str = ...) -> None: ...
def rpc_completion_callback(callback: Any): ...
def zero_or_greater(name: Any, value: Any) -> None: ...
